# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16917a41fb5aef5821188b7d747bae43"
name = "anime-ksp"
handle = "anime-ksp"
application_url = "https://bush-rankings-duty-interact.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "anime-ksp.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bush-rankings-duty-interact.trycloudflare.com/auth/callback",
  "https://bush-rankings-duty-interact.trycloudflare.com/auth/shopify/callback",
  "https://bush-rankings-duty-interact.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
